version: 2
jobs:
  build:
    docker:
      - image: $DOCKER_IMG
    working_directory: ~/ci_app
    environment:
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

    steps:
      - checkout

      - run:
          name: Download SFDX CLI
          command: |
            mkdir sfdx
            wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1

      - run:
          name: Install SFDX CLI
          command: |
            ./sfdx/install
            sfdx
            mkdir tmp

      - run:
          name: Create dev hub key
          command: |
            openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV 

      - run:
          name: Setup Org
          command: |
            sfdx force:auth:jwt:grant --clientid $HUB_CONSUMER_KEY --jwtkeyfile assets/server.key --username $HUB_SFDC_USER --setdefaultdevhubusername -a hub
            sfdx force:org:create -s -f ~/ci_app/config/project-scratch-def.json -a circle_build_$CIRCLE_BUILD_NUM --wait $WAIT_TIMEOUT
            sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM

      - run:
          name: Run Apex Tests
          command: |
            mkdir -p ~/junit
            sfdx force:apex:test:run -c -d ~/junit -r junit --wait $WAIT_TIMEOUT -u circle_build_$CIRCLE_BUILD_NUM

      - store_test_results:
          path: ~/junit

      - run:
          name: Delete Useless Scratch Org
          command: |
            sfdx force:org:delete -u circle_build_$CIRCLE_BUILD_NUM -p
